### ISSUE TITLE
Uninstalling wacom-tablet removes silabs vcp driver even if it is installed independently

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/homebrew-cask-drivers#1034]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Uninstalling cask wacom-tablet removes silabs vcp driver even if it is installed independently via cask silicon-labs-vcp-driver

#### Command that failed

```
brew cask uninstall wacom-tablet
```
Command did not fail, but also did not work as might be expected 

#### Output of command with `--force --verbose --debug`

Irrelevant

#### Output of `brew cask doctor`

Irrelevant

#### Output of `brew tap`

Irrelevant

The problem here is that if I have independently installed cask silicon-labs-vcp-driver, then it is because I know I have some device which relies on it. Uninstalling cask wacom-tablet should not remove the silabs vcp driver in this case, as it has been explicitly installed, presumably for some other piece of hardware.

**Comment by ralphrmartin** [comment]
I guess the same issue may also happen the other way round, too: removing cask silicon-labs-vcp-driver may cause breakage if wacom-tablet is installed.

It seems that cask wacom-tablet needs to be rewritten so that has silicon-labs-vcp-driver as a dependency, rather than duplicating / overlapping its functionality.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-drivers/pull/1035
