### ISSUE TITLE
Cask canon-pixma-scanner-driver-ica Fails Style Check

### ISSUE THREAD

**Issue by robertleeblairjr** [Homebrew/homebrew-cask-drivers#1252]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Cask canon-pixma-scanner-driver-ica fails style check.

#### Command that failed

```
brew cask style canon-pixma-scanner-driver-ica
```

#### Output of command with `--force --verbose --debug`

```
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cask/cmd/options.rb:65:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:43:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.13-54-geac74ec
==> macOS
10.15
==> SIP
Enabled
==> Java
1.8.0_222-zulu-8.40.0.25
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3471 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (163 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (934 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (135 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/portable-ruby
homebrew/services
koekeishiya/formulae
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
Does it work for any other cask? Because it looks more like you have a broken `style` command.

**Comment by robertleeblairjr** [comment]
> Does it work for any other cask? Because it looks more like you have a broken `style` command.

Here's the output of 'brew cask style' which should check all casks. I've even style checked individual cask files. This was the only one failing.

`== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/canon-pixma-scanner-driver-ica.rb ==
C: 10: 35: Prefer annotated tokens (like %<foo>s) over unannotated tokens (like %s).

4853 files inspected, 1 offense detected
Error: Style check failed.
`

**Comment by vitorgalvao** [comment]
@robertleeblairjr Why didn’t you put that in the top post? That’s the only part that mattered. It should’ve been in the `Description of issue`.

Also, you wanted a [fenced code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks), not backticks. Already fixed the post.

**Comment by vitorgalvao** [comment]
@reitermarkus I’ve read about annotated tokens, and I’m failing to see their usefulness or how they could be used in this situation. The [examples in Rubocop’s documentation](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/FormatStringToken) are particularly poor.

Is this a `style` check we should remove, or how do we comply?

**Comment by robertleeblairjr** [comment]
> @robertleeblairjr Why didn’t you put that in the top post? That’s the only part that mattered. It should’ve been in the `Description of issue`.
> 
> Also, you wanted a [fenced code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks), not backticks. Already fixed the post.

You do realize that people who contribute may not know certain aspects of submitting but also since they don't know are freely doing these things in their free time. You're snippy responses over a period have time have only shown me that you either don't know how to communicate with people or don't really care to improve on them. Fix it yourself since you want to be a d'bag about it.

**Comment by vitorgalvao** [comment]
@robertleeblairjr I apologise if my interactions to you sounded rude, as that was not my intention. I do, however, have to optimise for time because I too am doing this in my free time, and in a considerably larger scale — I interact with literally dozens of PRs and issues on a daily basis on this project alone. Being terse is a necessity.

I disagree I “don't know how to communicate with people” because the *vast* majority of users I interact with on this project don’t have an issue with the way I communicate with them. Over the years more have thanked me for my interactions than rebuked me. Still, I won’t pretend to be a paragon of virtue. I know that sometimes I fail, but I try to always recognise and fix it.

You may have read the fenced code block bit as ill-mannered, but others would have appreciated it for the new information, the link that explains it in depth, and for having it already fixed by the time they read the post, saving them the trouble. I know because that’s a variation on a standard reply that is usually appreciated.

I genuinely have no idea what you mean by “fix it yourself”, since nobody asked you to fix anything. I fixed your own post for you and asked another maintainer for a suggestion on how to proceed with the error you reported (and that we appreciate you doing so); there’s nothing else for you to do.

Read my posts as I wrote them — genuine questions and assertions — instead of accusations and criticisms, and you may see them as they were intended. My time with HBC has thought me to always read user posts as if they were written with a smile, because most times you read rudeness into something, it wasn’t there.

I do concede my compass may be a bit off these days because I’m currently sick, but I’m confident I haven’t resorted to name-calling, and would appreciate the same courtesy.

Still, I will reinforce my apology at having upset you. We can all have our bad days and deserve a pass. I don’t think it’s fair to make @reitermarkus have to reply after this exchange, so I’ll close and make a new issue for the question. Thank you again for the report.

**Comment by vitorgalvao** [comment]
New issue in https://github.com/Homebrew/homebrew-cask-drivers/issues/1253.

**Comment by robertleeblairjr** [comment]
> @robertleeblairjr I apologise if my interactions to you sounded rude, as that was not my intention. I do, however, have to optimise for time because I too am doing this in my free time, and in a considerably larger scale — I interact with literally dozens of PRs and issues on a daily basis on this project alone. Being terse is a necessity.
> 
> I disagree I “don't know how to communicate with people” because the _vast_ majority of users I interact with on this project don’t have an issue with the way I communicate with them. Over the years more have thanked me for my interactions than rebuked me. Still, I won’t pretend to be a paragon of virtue. I know that sometimes I fail, but I try to always recognise and fix it.
> 
> You may have read the fenced code block bit as ill-mannered, but others would have appreciated it for the new information, the link that explains it in depth, and for having it already fixed by the time they read the post, saving them the trouble. I know because that’s a variation on a standard reply that is usually appreciated.
> 
> I genuinely have no idea what you mean by “fix it yourself”, since nobody asked you to fix anything. I fixed your own post for you and asked another maintainer for a suggestion on how to proceed with the error you reported (and that we appreciate you doing so); there’s nothing else for you to do.
> 
> Read my posts as I wrote them — genuine questions and assertions — instead of accusations and criticisms, and you may see them as they were intended. My time with HBC has thought me to always read user posts as if they were written with a smile, because most times you read rudeness into something, it wasn’t there.
> 
> I do concede my compass may be a bit off these days because I’m currently sick, but I’m confident I haven’t resorted to name-calling, and would appreciate the same courtesy.
> 
> Still, I will reinforce my apology at having upset you. We can all have our bad days and deserve a pass. I don’t think it’s fair to make @reitermarkus have to reply after this exchange, so I’ll close and make a new issue for the question. Thank you again for the report.

I'm cool. However, my reply wasn't based upon this one response you've had with anything that I've posted. It's been quite a few times and I chose to not interpret past ones in a demeaning manner. But, I'm not mistaken when it comes to how you choose to reply to certain people. So, this one was just the straw that broke the camel's back in biting my tongue for ignoring them. I highly value criticism since I'm constantly learning but I definitely don't attempt to reply to someone with the intent that they're just making your job more difficult. A good portion of the people who do basic PR's are just as clueless as I am about the Ruby language or even better methods to submit PRs. However, I realize there's value in everyone no matter if it's nothing more than an update to versions for programs and they can do nothing more whether because of lack in knowledge or just mere time. Either way, it's forgotten now and moving on.
