### ISSUE TITLE
Prefer annotated tokens over unannotated tokens style check

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask-drivers#1253]
[`canon-pixma-scanner-driver-ica`](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/canon-pixma-scanner-driver-ica.rb) fails the `style` check with

```
C: 10: 35: Prefer annotated tokens (like %<foo>s) over unannotated tokens (like %s).
```

I’ve read about annotated tokens, and I’m failing to see their usefulness or how they could be used in this situation. The [examples in Rubocop’s documentation](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/FormatStringToken) are particularly poor.

Is this a `style` check we should remove? If not, how do we comply?

Pinging @reitermarkus.

**Comment by reitermarkus** [comment]
It should be

```ruby
format('%<major>02d%<minor>02d%<patch>02d', major: version.major, minor: version.minor, patch: version.patch)
```

now.

**Comment by vitorgalvao** [comment]
Thank you. Making the change.
