### ISSUE TITLE
Xerox printer drivers

### ISSUE THREAD

**Issue by krystof-k** [Homebrew/homebrew-cask-drivers#1393]
Question regarding [Xerox Print Driver](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/xerox-print-driver.rb) cask. The driver is for a specific printer, maybe the same for some others, but not for the one in mine case ([older Phaser 3250](https://www.support.xerox.com/support/phaser-3250/downloads/enus.html?operatingSystem=macos1012)). What is the correct approach to solve this?

**Comment by vitorgalvao** [comment]
> What is the correct approach to solve this?

Rename that one ([something like this](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/fujitsu-scansnap-manager-ix500.rb)) and add yours with a name following the same rule.

**Comment by krystof-k** [comment]
Hmm:
> This product is no longer supported when running on macOS® 10.12.5 or higher
Nevermind…
