### ISSUE TITLE
zsa-wally: image also provides a command line binary

### ISSUE THREAD

**Issue by devster31** [Homebrew/homebrew-cask-drivers#1398]
#### Description of issue

The .dmg image contains both `Wally.app` and `wally-cli`. Currently only the app is being moved by the `app` stanza.
https://github.com/Homebrew/homebrew-cask-drivers/blob/0614c6948dea17f06da97337b2f47e61527aec3c/Casks/zsa-wally.rb#L11
Would it be useful to add an `artifact` stanza for the command line utility?

**Comment by vitorgalvao** [comment]
> Would it be useful to add an `artifact` stanza for the command line utility?

`binary`, not `artifact`, but yes. Please submit a PR.
