### ISSUE TITLE
ubiquiti-unifi-controller - open /Applications/UniFi.app shows "Unable to load Java Runtime Environment."

### ISSUE THREAD

**Issue by rgaufman** [Homebrew/homebrew-cask-drivers#1577]
I ran:

```
$ brew cask install ubiquiti-unifi-controller
```

When I try to launch it, I see this:
![Screenshot 2020-05-17 at 15 37 19](https://user-images.githubusercontent.com/33842342/82151627-4de8d200-9854-11ea-904c-693196a1d5d1.png)

Any ideas?

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
