### ISSUE TITLE
Cask suggestion: j5create ethernet adapters &c.

### ISSUE THREAD

**Issue by jakewilliami** [Homebrew/homebrew-cask-drivers#1610]
## Suggestion and Caveats

Not a cask request, but more a question of how I'd go about making a pull request (or if it's worth it).

I'd love to see some support for j5create drivers.  However, it seems like it might be a little convoluted.  Instead of having separate downloads for each adapter, you have one dmg downloaded (for example, looking at the USB ethernet adapter), which has two pkg installers in it: one for the models of adapter JUE125 and JUE120; the other for models JCE131, JCH471, JCA374, JUE130, JUH470, and JUE230.

Futhermore, though this driver worked on my macOS 10.14, my partner's macOS 10.15 required a **whole other driver** that wasn't labelled for the device: downloadable [here, labelled j5create Dock and Video Adapter Driver](https://download.j5create.com/driver/USB_3.0_Multi_Adapter_Mac_Driver/J5Create_Dock_and_Video_Adapter_Driver-3.3-2019-12-05a.dmg).

So what do you all reckon?  Do you think it's possible to add support for something like this, or is it too much work for what it's worth?

## My attempt
What follows is a very bare-bones, certainly incomplete structure to the j5create drivers for the USB ethernet adapters:
```ruby
cask 'j5create-usb-ethernet-adapters' do
    version '2.9.0-2.5.0'
    sha256 :no_check

    # download.j5create.com/ was verified as official when first introduced to the cask
    url 'https://download.j5create.com/driver/V2.9.0_Ethernet_Adapter_Driver/j5UsbEthernetAdapter-v2.9.0-2.5.0-mac.dmg'
    name 'j5create USB Ethernet Adapters'
    homepage 'https://info.j5create.com/'
    zap trash: [
                /Library/Extensions/AX88772,
	        /Library/Extensions/AX88179_178a,
	        /Library/Extensions/MCT_trigger2.kext,
	        /Library/Extensions/Trigger5Core.kext,
	        /Library/Extensions/DJTVirtualDisplayDriver,
	        /Library/Extensions/MCTDisplay.kext,
	        /Library/Extensions/MCTTrigger6USB,
	        /Library/Extensions/MCTTTriggerGraphics.plugin,
               ]
end
```

---

## Notes
- There requires a restart after installing the drivers.
- The trash array in the zap stanza may not be complete for this driver, and may not be applicable to other j5create drivers.
- There are certain things the pkg installers require you to 'accept' in your system preferences if running manually.  Not sure if `sudo installer -pkg ...` will overcome these steps.

**Comment by vitorgalvao** [comment]
> is it too much work for what it's worth?

Yes. But thank you for asking.
