### ISSUE TITLE
Razer Synapse not supported on macos > 10.14

### ISSUE THREAD

**Issue by onyxraven** [Homebrew/homebrew-cask-drivers#1744]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).

#### Description of issue

Razer Synapse is no longer supported on MacOS - the last supported version is Synapse 2 on 10.14. See [their official page](https://support.razer.com/articles/1657604171).

The razer-synapse cask installs and appears to run, but login and functionality does not work.

Adding an OS version check to this cask would be recommended.

**Comment by vitorgalvao** [comment]
Thank you for the report.

https://github.com/Homebrew/homebrew-cask-drivers/pull/1746.

**Comment by onyxraven** [comment]
Thanks!
