### ISSUE TITLE
ASIX AX88179 Big Sur drivers

### ISSUE THREAD

**Issue by ericswpark** [Homebrew/homebrew-cask-drivers#2226]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

The current AX88179 formula downloads version 2.19.0, which is for macOS 10.15 and below. For Big Sur, there is another driver (possibly to fix the kext driver problem). The latest release for Big Sur is version 1.1.0d2, released on May 11, 2021.

Here is a link to the new download: https://www.asix.com.tw/en/support/download/file/1113

I'm not sure how to edit the formula so that it downloads this new driver for Big Sur only, but the current formula downloads the incorrect driver for the macOS version.

### Command that failed

brew install asix-ax88179

**Comment by carlocab** [comment]
See these for examples:

```
Casks/logitech-unifying.rb
Casks/sound-blaster-play3.rb
Casks/concept2-utility.rb
Casks/nvidia-cuda-toolkit.rb
Casks/garmin-basecamp.rb
Casks/roland-quad-capture-usb-driver.rb
Casks/elgato-game-capture-hd.rb
Casks/konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver.rb
Casks/displaylink.rb
Casks/nvidia-web-driver.rb
Casks/konica-minolta-bizhub-c750i-driver.rb
Casks/logitech-options.rb
Casks/xerox-print-driver.rb
```

**Comment by ericswpark** [comment]
Thanks @carlocab, just pushed a PR with the changes.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask-drivers/pull/2231.
