### ISSUE TITLE
cannot install asix-ax88179

### ISSUE THREAD

**Issue by zhangyoufu** [Homebrew/homebrew-cask-drivers#2296]
I followed the manual installation instruction like this
```
% open /usr/local/Caskroom/asix-ax88179/2.19.0,1109/AX88179_178A_v2.19.0.app
```
While the installer does not pop-up at all.

I tried to run the executable directly and met some error.
```
% /usr/local/Caskroom/asix-ax88179/2.19.0,1109/AX88179_178A_v2.19.0.app/Contents/MacOS/AX88179
The file /Volumes/AX88179_178A/.AX88179_178A_10.15.pkg does not exist.
```

I have to do something like this as a workaround to run the installer app.
```
% sudo ln -s /usr/local/Caskroom/asix-ax88179/2.19.0,1109 /Volumes/AX88179_178A
```

Maybe we can just skip the app and install the pkg directly?

**Comment by miccal** [comment]
Did you `reboot` as stated in the `caveats`?

**Comment by zhangyoufu** [comment]
I don't think this issue has anything to do with reboot.

The app specified by `installer manual:` is hard-coded with `/Volumes/AX88179_178A/` path, which simply does not exist because files inside dmg are copied to `/usr/local/Caskroom/asix-ax88179/#{version}/`.

**Comment by vitorgalvao** [comment]
> Maybe we can just skip the app and install the pkg directly?

I there is one, sure, that would be preferred.

**Comment by cho-m** [comment]
At this point, having a user test a few cask changes out locally will help.

It does look like 2 dot-prefixed PKG files exist (one for Catalina, the other for everything older):
```console
❯ ls -a /Volumes/AX88179_178A
.   AX88179_178A_v2.19.0.app  .AX88179_178A_10.9_10.14.pkg  AX88179_178A_Uninstall_v1.8.0.pkg
..  .AX88179_178A_10.15.pkg   .DS_Store                     readme.txt
```

Whether we can run these directly and non-interactively is something that needs to be tried out.

One thing to try would be modifying installation method locally to run non-interactive PKG install for Catalina:
- Old: `installer manual: "AX88179_178A_v#{version.before_comma}.app"`
- New: `pkg ".AX88179_178A_10.15.pkg"`

---

On side note, the `asix-ax88179` cask has been giving us some trouble recently.

Right now:
- This issue shows that Catalina and older installation may be broken.
- Another issue (Homebrew/homebrew-cask#106820) along with the last failed update attempt (#2250) shows that Big Sur is broken.

**Comment by miccal** [comment]
For `MacOS.version <= :catalina` corresponding to version `2.19.0`, there is no `.pkg` for the install, there is only an `.app`:

<img width="426" alt="Screen Shot 2021-06-27 at 01 56 56" src="https://user-images.githubusercontent.com/6127163/123521722-01c0c000-d6eb-11eb-990b-cf35a4d41a85.png">

There is only ` .pkg` for the `uninstall`.

What happens if you download this version manually and run the `.app`?

**Comment by zhangyoufu** [comment]
> For `MacOS.version <= :catalina` corresponding to version `2.19.0`, there is no `.pkg` for the install, there is only an `.app`:
> 
> <img alt="Screen Shot 2021-06-27 at 01 56 56" width="426" src="https://user-images.githubusercontent.com/6127163/123521722-01c0c000-d6eb-11eb-990b-cf35a4d41a85.png">
> 
> There is only ` .pkg` for the `uninstall`.

The installation packages are hidden (prefixed with dot)

**Comment by miccal** [comment]
@vitorgalvao are hidden files inside `.dmg`'s also moved to `Caskroom`?

**Comment by vitorgalvao** [comment]
> @vitorgalvao are hidden files inside `.dmg`'s also moved to `Caskroom`?

They should be, as this isn’t the only software that hides stuff in the dmg. But @reitermarkus should be able to say for sure.
