### ISSUE TITLE
Incorrect shasum opentx-companion

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/homebrew-cask-drivers#2310]
https://github.com/Homebrew/homebrew-cask-drivers/blob/b8a9ca2eea99924272f00cfdd8fb0bcc43ede553/Casks/opentx-companion.rb#L3

shasum --algorithm 256 opentx-companion-2.3.13.dmg

ced629c0a8c738cecf2a683f02eeadfd38211d2a2ef152331b7c415ac65b8406

Not sure why anything changed here. Downloading direct from the website I'm getting something different. It installs just fine.

**Comment by carlocab** [comment]
Here's our documentation on checksum mismatches: https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md

When reporting problems, please use the issue template. Not providing the information requested there just makes it so much harder to diagnose and fix problems.
