### ISSUE TITLE
No unattended logi-options-plus installation

### ISSUE THREAD

**Issue by ashokm** [Homebrew/homebrew-cask-drivers#3222]
When installing the [logi-options-plus](https://github.com/Homebrew/homebrew-cask-drivers/blob/9a8b9accbc97391bc135cd8b5a66a9e26cab5161/Casks/logi-options-plus.rb) cask to install [Logi Options+](https://www.logitech.com/en-ca/software/logi-options-plus.html), the user still has to perform additional manual steps to complete the installation:

```bash
$ brew install logi-options-plus
==> Caveats
You must reboot for the installation of logi-options-plus to take effect.

==> Downloading https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.zip
######################################################################## 100.0%
Warning: No checksum defined for cask 'logi-options-plus', skipping verification.
==> Installing Cask logi-options-plus
To complete the installation of Cask logi-options-plus, you must also
run the installer at:
  /opt/homebrew/Caskroom/logi-options-plus/1.30.0.7349/logioptionsplus_installer.app
🍺  logi-options-plus was successfully installed!
```

It would be great if there was a way to automate this, so the user does not have to manually run the installer:

```bash
open /opt/homebrew/Caskroom/logi-options-plus/1.30.0.7349/logioptionsplus_installer.app
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/issues/24377
