### ISSUE TITLE
Migrate casks to homebrew/cask.

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/homebrew-cask-drivers#3414]
@Homebrew/members please migrate any drivers you are using yourself to homebrew/cask. 

For the remaining ones, we'll use some TBD threshold to decide if we want to migrate them or delete them.

**Comment by p-linnane** [comment]
I do not personally use anything from this repo, but I am happy to help the migration effort when we decide what to do with what is left.

**Comment by razvanazamfirei** [comment]
<details>
<summary>Download Count</summary>
<table>
<tr>
    <td>synology-drive
    <td>4,608
<tr>
    <td>qmk-toolbox
    <td>4,253
<tr>
    <td>cameracontroller
    <td>4,126
<tr>
    <td>logi-options-plus
    <td>4,099
<tr>
    <td>sonos
    <td>1,153
<tr>
    <td>garmin-express
    <td>680
<tr>
    <td>yubico-authenticator
    <td>613
<tr>
    <td>jabra-direct
    <td>497
<tr>
    <td>wacom-tablet
    <td>490
<tr>
    <td>logitech-unifying
    <td>457
<tr>
    <td>nordic-nrf-command-line-tools
    <td>376
<tr>
    <td>elgato-control-center
    <td>373
<tr>
    <td>yubico-yubikey-personalization-gui
    <td>310
<tr>
    <td>zsa-wally
    <td>309
<tr>
    <td>displaylink-login-extension
    <td>299
<tr>
    <td>logitech-firmwareupdatetool
    <td>259
<tr>
    <td>silicon-labs-vcp-driver
    <td>226
<tr>
    <td>philips-hue-sync
    <td>215
<tr>
    <td>lg-onscreen-control
    <td>205
<tr>
    <td>focusrite-control
    <td>202
<tr>
    <td>fujitsu-scansnap-home
    <td>193
<tr>
    <td>steelseries-exactmouse-tool
    <td>192
<tr>
    <td>hp-easy-start
    <td>183
<tr>
    <td>qflipper
    <td>183
<tr>
    <td>elgato-camera-hub
    <td>169
<tr>
    <td>yubico-yubikey-piv-manager
    <td>167
<tr>
    <td>wch-ch34x-usb-serial-driver
    <td>158
<tr>
    <td>synologyassistant
    <td>151
<tr>
    <td>xbox360-controller-driver-unofficial
    <td>146
<tr>
    <td>canon-eos-webcam-utility
    <td>143
<tr>
    <td>logitech-gaming-software
    <td>138
<tr>
    <td>steelseries-gg
    <td>132
<tr>
    <td>nitrokey
    <td>130
<tr>
    <td>gutenprint
    <td>120
<tr>
    <td>logitech-control-center
    <td>112
<tr>
    <td>asix-ax88179
    <td>109
<tr>
    <td>prolific-pl2303
    <td>109
<tr>
    <td>steelseries-engine
    <td>109
<tr>
    <td>xerox-print-driver
    <td>101
<tr>
    <td>caldigit-docking-utility
    <td>99
<tr>
    <td>insta360-studio
    <td>99
<tr>
    <td>garmin-basecamp
    <td>98
<tr>
    <td>1kc-razer
    <td>96
<tr>
    <td>8bitdo-firmware-updater
    <td>94
<tr>
    <td>ftdi-vcp-driver
    <td>90
<tr>
    <td>plantronics-hub
    <td>90
<tr>
    <td>nordic-nrf-connect
    <td>84
<tr>
    <td>tiptoi-manager
    <td>82
<tr>
    <td>saleae-logic
    <td>80
<tr>
    <td>kyocera-printer-drivers
    <td>78
<tr>
    <td>apple-hewlett-packard-printer-drivers
    <td>67
<tr>
    <td>bose-updater
    <td>64
<tr>
    <td>obinskit
    <td>63
<tr>
    <td>hhkb-keymap-tool
    <td>62
<tr>
    <td>obs-ios-camera-source
    <td>62
<tr>
    <td>rode-central
    <td>61
<tr>
    <td>luna-display
    <td>59
<tr>
    <td>hdhomerun
    <td>58
<tr>
    <td>pallotron-yubiswitch
    <td>56
<tr>
    <td>fujitsu-scansnap-manager
    <td>54
<tr>
    <td>shureplus-motiv
    <td>54
<tr>
    <td>konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver
    <td>53
<tr>
    <td>caldigit-thunderbolt-charging
    <td>52
<tr>
    <td>dymo-label
    <td>51
<tr>
    <td>samsung-portable-ssd-t5
    <td>51
<tr>
    <td>droidcam-obs
    <td>50
<tr>
    <td>synology-surveillance-station-client
    <td>50
<tr>
    <td>blue-sherpa
    <td>49
<tr>
    <td>elgato-game-capture-hd
    <td>45
<tr>
    <td>drobo-dashboard
    <td>44
<tr>
    <td>uhk-agent
    <td>43
<tr>
    <td>3dconnexion
    <td>40
<tr>
    <td>canon-mf-printer
    <td>40
<tr>
    <td>reolink-client
    <td>39
<tr>
    <td>huiontablet
    <td>38
<tr>
    <td>flashforge-flashprint
    <td>35
<tr>
    <td>elecom-mouse-assistant
    <td>34
<tr>
    <td>brother-p-touch-update-software
    <td>33
<tr>
    <td>motu-m-series
    <td>33
<tr>
    <td>obsbot-tinycam
    <td>33
<tr>
    <td>fujifilm-x-raw-studio
    <td>32
<tr>
    <td>muteme
    <td>31
<tr>
    <td>fujifilm-x-webcam
    <td>29
<tr>
    <td>wd-security
    <td>28
<tr>
    <td>audient-evo
    <td>27
<tr>
    <td>loupedeck
    <td>27
<tr>
    <td>logitune
    <td>25
<tr>
    <td>lg-dual-controller
    <td>23
<tr>
    <td>elektron-transfer
    <td>22
<tr>
    <td>netgear-switch-discovery-tool
    <td>22
<tr>
    <td>synology-photo-station-uploader
    <td>22
<tr>
    <td>luna-secondary
    <td>20
<tr>
    <td>sandisk-security
    <td>20
<tr>
    <td>fujifilm-x-acquire
    <td>19
<tr>
    <td>concept2-utility
    <td>18
<tr>
    <td>elektron-overbridge
    <td>18
<tr>
    <td>fujitsu-scansnap-manager-ix500
    <td>18
<tr>
    <td>samsung-portable-ssd-t7
    <td>18
<tr>
    <td>xppen-pentablet
    <td>18
<tr>
    <td>hhkb-pro-driver
    <td>17
<tr>
    <td>qnap-external-raid-manager
    <td>17
<tr>
    <td>ricoh-ps-printers-vol4-exp-driver
    <td>17
<tr>
    <td>segger-ozone
    <td>17
<tr>
    <td>ubiquiti-unifi-controller-lts
    <td>17
<tr>
    <td>focusrite-saffire-mixcontrol
    <td>16
<tr>
    <td>safenet-authentication-client
    <td>16
<tr>
    <td>wd-drive-utilities
    <td>16
<tr>
    <td>behringer-x32-edit
    <td>15
<tr>
    <td>obsbot-me-tool
    <td>15
<tr>
    <td>elgato-thunderbolt-dock
    <td>14
<tr>
    <td>playdate-mirror
    <td>14
<tr>
    <td>roli-connect
    <td>14
<tr>
    <td>yamaha-usb-midi-driver
    <td>14
<tr>
    <td>blackvue-viewer
    <td>13
<tr>
    <td>canon-ijscanner6
    <td>13
<tr>
    <td>canon-mf-ufr2-printer
    <td>13
<tr>
    <td>hp-connectivity-kit
    <td>13
<tr>
    <td>eobcanka
    <td>12
<tr>
    <td>fitbit-connect
    <td>12
<tr>
    <td>ricoh-theta
    <td>12
<tr>
    <td>wd-firmware-updater
    <td>12
<tr>
    <td>datacolor-spyder-pro
    <td>11
<tr>
    <td>calibrite-ccprofiler
    <td>10
<tr>
    <td>cardo-update
    <td>10
<tr>
    <td>epson-photo-plus
    <td>10
<tr>
    <td>garmin-virb-edit
    <td>10
<tr>
    <td>ricoh-ps-printers-vol3-exp-driver
    <td>10
<tr>
    <td>canon-captureontouch-utility
    <td>9
<tr>
    <td>canon-ijscanner1
    <td>9
<tr>
    <td>focusrite-thunderbolt
    <td>9
<tr>
    <td>lmsclients-squeezeplay
    <td>9
<tr>
    <td>nvidia-cuda-toolkit
    <td>9
<tr>
    <td>eizo-colornavigator
    <td>8
<tr>
    <td>opal
    <td>8
<tr>
    <td>synology-cloud-station-backup
    <td>8
<tr>
    <td>tomtom-sports-connect
    <td>8
<tr>
    <td>epson-print-layout
    <td>7
<tr>
    <td>epson-surecolor-p900
    <td>7
<tr>
    <td>gk6-plus
    <td>7
<tr>
    <td>lovense-remote
    <td>7
<tr>
    <td>obsbot-webcam
    <td>7
<tr>
    <td>reinersct-cyberjack
    <td>7
<tr>
    <td>roland-quad-capture-usb-driver
    <td>7
<tr>
    <td>sound-blaster-play3
    <td>7
<tr>
    <td>canon-ijscanner13f
    <td>6
<tr>
    <td>cycliqplus-firmware-updater
    <td>6
<tr>
    <td>opentx-companion
    <td>6
<tr>
    <td>toneprint
    <td>6
<tr>
    <td>cycliq-cycliqplus
    <td>5
<tr>
    <td>evolv-escribe-suite
    <td>5
<tr>
    <td>rjm-megxeditor
    <td>5
<tr>
    <td>acs-acr39u-smartcard-driver
    <td>4
<tr>
    <td>camengine
    <td>4
<tr>
    <td>canon-ijscanner2
    <td>4
<tr>
    <td>canon-ijscanner4
    <td>4
<tr>
    <td>canon-ijscanner15f
    <td>4
<tr>
    <td>canon-pixma25xx-printer
    <td>4
<tr>
    <td>clavia-nord-sound-manager
    <td>4
<tr>
    <td>konica-minolta-bizhub-c220-c280-c360-driver
    <td>4
<tr>
    <td>nvidia-web-driver
    <td>4
<tr>
    <td>openintelwireless-heliport
    <td>4
<tr>
    <td>picoscope
    <td>4
<tr>
    <td>rjm-mmgteditor
    <td>4
<tr>
    <td>seagate-dashboard
    <td>4
<tr>
    <td>smartscope
    <td>4
<tr>
    <td>sony-xperia-companion
    <td>4
<tr>
    <td>bose-soundtouch
    <td>3
<tr>
    <td>bose-usb-link-updater
    <td>3
<tr>
    <td>canon-ijscanner5
    <td>3
<tr>
    <td>canon-ijscanner14f
    <td>3
<tr>
    <td>canon-ijscanner16f
    <td>3
<tr>
    <td>creative-sb-command
    <td>3
<tr>
    <td>genki-softwave
    <td>3
<tr>
    <td>kiibohd-configurator
    <td>3
<tr>
    <td>mazda-toolbox
    <td>3
<tr>
    <td>mimu-glover
    <td>3
<tr>
    <td>razer-synapse
    <td>3
<tr>
    <td>tomtom-mydrive-connect
    <td>3
<tr>
    <td>canon-ijscanner3
    <td>2
<tr>
    <td>canon-imageformula-driver
    <td>2
<tr>
    <td>canon-print-studio-pro
    <td>2
<tr>
    <td>datacolor-spyder-elite
    <td>2
<tr>
    <td>fnatic-op
    <td>2
<tr>
    <td>g-raid-with-thunderbolt-configurator
    <td>2
<tr>
    <td>kensington-trackball-works
    <td>2
<tr>
    <td>rapoo-mt750s
    <td>2
<tr>
    <td>sony-rcs300
    <td>2
<tr>
    <td>blocks-code
    <td>1
<tr>
    <td>canon-pixma72xx-printer
    <td>1
<tr>
    <td>canon-scangear-mf
    <td>1
<tr>
    <td>creative
    <td>1
<tr>
    <td>datacolor-spyder-express
    <td>1
<tr>
    <td>genki-wave-for-work
    <td>1
<tr>
    <td>interstuhl-s40
    <td>1
<tr>
    <td>logitech-myharmony
    <td>1
<tr>
    <td>ni-488-2
    <td>1
<tr>
    <td>phidget-control-panel
    <td>1
</table>
</details>

**Comment by MikeMcQuaid** [comment]
(I have previously used `philips-hue-sync` and `logitech-myharmony` too).

There's some debate to me about which ones of these are even "drivers" so: again 👍🏻 👏🏻 🎉 on moving these into homebrew-cask proper.

**Comment by reitermarkus** [comment]
Little guide:

1. Add to `tap_migrations.json` here.
2. Move cask file into homebrew/cask tap.

> which ones of these are even "drivers"

It's pretty loosely defined for this repo: Software which isn't useful without dedicated hardware.

**Comment by colindean** [comment]
Going through what's here, here's what I use or have used in the past and would like to have available some day until something breaks:

- [ ] cameracontroller
- [ ] displaylink-login-extension (although a quick read of [the homepage](https://support.displaylink.com/knowledgebase/articles/1932214-displaylink-manager-app-for-macos-introduction-in#other) leads me to believe that it's no longer needed for macOS 11+…?
- [ ] droidcam-obs
- [ ] elgato-game-capture-hd
- [ ] fitbit-connect
- [ ] gutenprint
- [ ] obsbot-webcam
- [ ] ricoh-theta
- [ ] steelseries-engine

obsbot-tinycam can be deprecated because obsbot-webcam replaced it.

I'll move these over if no ones gets to them before I do using https://github.com/Homebrew/homebrew-cask/pull/145008 and https://github.com/Homebrew/homebrew-cask-drivers/pull/3415 as examples.

**Comment by colindean** [comment]
@razvanazamfirei Thank you!

**Comment by bevanjkay** [comment]
Just found two more that I use on other machines.
https://github.com/Homebrew/homebrew-cask/pull/145119

**Comment by ifonefox** [comment]
Why is cask-drivers being discontinued?

**Comment by reitermarkus** [comment]
@ifonefox, if you're using a cask that is in here, you can submit a PR to move it to `homebrew/cask`. Having everything in one repo is easier to maintain.

**Comment by reitermarkus** [comment]
@razvanazamfirei, could you update your comment above when you get a chance? Thanks.

**Comment by razvanazamfirei** [comment]
Done!

**Comment by reitermarkus** [comment]
The casks remaining now have > 100 installs and had an update in the last few months.

**Comment by acidghost** [comment]
> @ifonefox, if you're using a cask that is in here, you can submit a PR to move it to `homebrew/cask`. Having everything in one repo is easier to maintain.

@reitermarkus I just realized that 1kc-razer has been deleted from this tap (I had no idea of the plans to merge this tap into the main cask).

Given that 1kc-razer has already been removed, should I just open a new issue / PR on homebrew/cask with a copy of the formula that once was here?

**Comment by reitermarkus** [comment]
@acidghost, yes, please go ahead and submit it to `homebrew/cask` and add it to `tap_migrations.json` here.

**Comment by razvanazamfirei** [comment]
Yes, please submit the PRs and we can migrate it.

**Comment by pascal-hofmann** [comment]
It would be great to have `insta360-studio` and `tiptoi-manager` migrated.

**Comment by razvanazamfirei** [comment]
@pascal-hofmann migrated!

**Comment by ivicamil** [comment]
@reitermarkus 

I've created a [PR](https://github.com/Homebrew/homebrew-cask/pull/146944) for migrating `focusrite-control` that was deleted from here, but some CI tests failed. I don't know why as I installed the formula about 2 weeks ago on my Mac and it worked perfectly fine. It is the most recent version of the Focusrite Control software.

**Comment by pascal-hofmann** [comment]
@razvanazamfirei Awesome, thank you! 🚀

**Comment by aranw** [comment]
Hey I was previously installing `audient-evo` from this cask but it's appeared to have been removed and was wondering what is the process to either use an older version of this cask in homebrew or migrating the cask into homebrew/casks? 

Trying to setup a new laptop right now and it's failing on the install of this cask
