### ISSUE TITLE
pololu-avr-programmer-v2 was removed despite being used and still up to date

### ISSUE THREAD

**Issue by Kreeblah** [Homebrew/homebrew-cask-drivers#3445]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

https://github.com/Homebrew/homebrew-cask-drivers/pull/3444 removed a number of casks which had fewer than 100 downloads.  Since there were some that had more than 100 downloads, there was a proposal that they be removed if they hadn't been updated in a while.

It looks like `pololu-ave-programmer-v2` was caught up in this, even though the cask still refers to the latest released package (which `brew livecheck --cask pololu-avr-programmer-v2` agrees with).

Could this be re-added?

### Command that failed

N/A

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by reitermarkus** [comment]
> the cask still refers to the latest released package

This was released 2 years ago, which is why it was removed.

> Could this be re-added?

Yes, feel free to submit it to `homebrew/cask` instead and add it to `tap_migrations.json` here.

**Comment by razvanazamfirei** [comment]
Migrated! Thank you, @Kreeblah!
