### ISSUE TITLE
Changed download location of tools

### ISSUE THREAD

**Issue by prentesvarten** [Homebrew/homebrew-cask-drivers#673]
Nordic in their infinite wisdom changed the location of tools.

https://www.nordicsemi.com/Software-and-Tools/Development-Tools/nRF5-Command-Line-Tools/Download#infotabs

**Comment by vitorgalvao** [comment]
Thank you, but next time please be specific. We’ll act faster (or at all) if we know exactly which casks you’re talking about. Or better yet, if you submit a PR.

I’ll have a fix soon.

**Comment by vitorgalvao** [comment]
Actually, can’t do it right now because it seems they don’t have a clear versioned replacement. Going to need a PR for that.

**Comment by ytbmulder** [comment]
I opened pull request #676 to fix this issue.

**Comment by vitorgalvao** [comment]
Thank you as always, @ytbmulder.
